# specify configuration version is a must except if using circleci server
version: 2.1

workflows:
  # name of the workflow
  test-deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/node:17.4.0
    steps:
      - checkout
      - run: node --version
